### ISSUE TITLE
Request to update proot-static with proot >5.1.107-45

### ISSUE THREAD

**Issue by WheezyE** [ZhymabekRoman/proot-static#2]
Hello again,

It took me a while to figure out how to fix [AnBox86](https://github.com/WheezyE/AnBox86/blob/WheezyE-patch-1/AnBox86.sh) with the newer proot-distro distros/installers, but I've found a method.  I realized, however, that though everything is working (with proot-static's help) the user accounts and sudo permissions aren't working in proot-static.  These accounts/permissions do work in the latest proot. So I believe these permissions errors in proot-static are due to proot-static using [an older version of proot that had errors with user accounts](https://github.com/termux/proot/issues/193#issuecomment-932979361).  Would it be possible to update proot-static with the latest proot?

Hope you're doing well and staying safe out there.

**Comment by ZhymabekRoman** [comment]
Hello, I live in Kazakhstan, and we have serious interruptions in the Internet. As the situation stabilizes I will update the proot-static. Perhaps even write a Github CI script that will automatically update proot-static based on the proot repository.

**Comment by WheezyE** [comment]
No rush at all.  A Github CI would be wonderful too. Thank you for your
work on proot-static.

I just happened to have some time to work on AnBox86 again after a long
while.

Take your time and take care, my friend

**Comment by ZhymabekRoman** [comment]
Hello, I apologize for not responding for a long time. I updated proot-static to the latest version, and tested on a basic level - everything seems to work fine.

Best regards,
Roman.

**Comment by WheezyE** [comment]
No worries at all. Glad to hear you’re doing well. Thank you 🙂
